### ISSUE TITLE
Fatal exception when dialing

### ISSUE THREAD

**Issue by mrjaimisra** [webex/spark-android-sdk#31]
Hello,

Whenever I attempt to dial, I receive a strange error:

```
2019-04-02 19:31:18.311 5964-5998/com.vhcios I/PhoneImpl:505: mqt_native_modules  Dialing: 626532151@meetnyvhc-test.webex.com, true
2019-04-02 19:31:18.312 1650-1660/? I/ActivityManager: START u0 {flg=0x10000000 cmp=com.vhcios/com.ciscowebex.androidsdk.internal.AcquirePermissionActivity (has extras)} from uid 10078 on display 0
2019-04-02 19:31:18.334 5964-5964/com.vhcios D/AcquirePermissionActivity:79: main  request PERMISSION_CAMERA_MIC
2019-04-02 19:31:18.335 5964-5964/com.vhcios I/AcquirePermissionActivity:103: main  Do not need request permission, and make call directly
2019-04-02 19:31:18.335 5964-5964/com.vhcios D/PhoneImpl:473: main  make outgoing call
2019-04-02 19:31:18.336 5964-5964/com.vhcios D/PhoneImpl:1527: main  Dial 626532151@meetnyvhc-test.webex.com
2019-04-02 19:31:18.336 5964-5964/com.vhcios I/CallControlService:433: main  CallControlService.connectToCall, -------------------------------------------------------------------------------------------------------
2019-04-02 19:31:18.336 5964-5964/com.vhcios I/CallControlService:434: main  CallControlService.joinCall, locusKey = null, invitee = 626532151@meetnyvhc-test.webex.com, isOneOnOne = true, isAutoJoin = false, isWirelessScreenShare = false
2019-04-02 19:31:18.337 5964-5964/com.vhcios I/CallControlService:436: main  CallControlService.connectToCall, -------------------------------------------------------------------------------------------------------
2019-04-02 19:31:18.346 5964-5964/com.vhcios I/CallControlService:487: main  CallControlService.joinCall, mediaEngine.isInitialized() == false, call mediaEngine.initialize().
2019-04-02 19:31:18.346 5964-5964/com.vhcios I/MediaSessionEngine:116: main  MediaSessionEngine.initialize(), MediaSessionEngine initialized = false
2019-04-02 19:31:18.347 5964-5964/com.vhcios E/art: No implementation found for void com.webex.wme.NativeMediaSession.initWME() (tried Java_com_webex_wme_NativeMediaSession_initWME and Java_com_webex_wme_NativeMediaSession_initWME__)
2019-04-02 19:31:18.347 5964-5964/com.vhcios D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-04-02 19:31:18.347 5964-5964/com.vhcios E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vhcios, PID: 5964
    java.lang.UnsatisfiedLinkError: No implementation found for void com.webex.wme.NativeMediaSession.initWME() (tried Java_com_webex_wme_NativeMediaSession_initWME and Java_com_webex_wme_NativeMediaSession_initWME__)
        at com.webex.wme.NativeMediaSession.initWME(Native Method)
        at com.cisco.spark.android.media.MediaSessionEngine.initialize(MediaSessionEngine.java:122)
        at com.cisco.spark.android.callcontrol.CallControlService.connectToCall(CallControlService.java:488)
        at com.cisco.spark.android.callcontrol.CallControlService.joinCall(CallControlService.java:418)
        at com.ciscowebex.androidsdk.phone.internal.PhoneImpl.doDial(PhoneImpl.java:1531)
        at com.ciscowebex.androidsdk.phone.internal.PhoneImpl.makeCall(PhoneImpl.java:491)
        at com.ciscowebex.androidsdk.phone.internal.RotationHandler.makeCall(RotationHandler.java:80)
        at com.ciscowebex.androidsdk.internal.AcquirePermissionActivity.onCreate(AcquirePermissionActivity.java:104)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

Here is my dial method:

```
@ReactMethod
    public void dial(String dialAddr, Promise promise) {
        Log.i("Phone Module", "Dialing: " + dialAddr);
        WebExTeamsGlobal.phone.setDefaultFacingMode(Phone.FacingMode.USER);
        //SparkGlobal.phone.startPreview(SparkGlobal.localView);
//        MediaOption mediaOption = WebExTeamsGlobal.getMediaOption();
//        Log.i("Spark Phone", "Remote view height: " + mediaOption.getRemoteView().getHeight());
        WebExTeamsGlobal.phone.dial(dialAddr, MediaOption.audioVideo(WebExTeamsGlobal.localView, WebExTeamsGlobal.remoteView), (result) -> {
            if (result.isSuccessful()) {
                Log.i("Spark Phone", "Dialed Successfully");
                WebExTeamsGlobal.call = result.getData();
//                SparkGlobal.call.setFacingMode(Phone.FacingMode.USER);
                WebExTeamsGlobal.call.setSendingAudio(true);
                WebExTeamsGlobal.call.setReceivingAudio(true);
//                SparkGlobal.call.setSendingVideo(true);
                WebExTeamsGlobal.call.setReceivingVideo(true);


                CallObserver callObserver = new CallObserver() {
                    @Override
                    public void onRinging(Call call) {
                        Log.i("Spark Call", "Ringing...");
                    }

                    @Override
                    public void onConnected(Call call) {
                        Log.i("Spark Call", "Remote video view size: " + call.getRemoteVideoViewSize().flattenToString());
                        Log.i("Spark Call", "Local video view size: " + call.getLocalVideoViewSize().flattenToString());
                    }

                    @Override
                    public void onDisconnected(CallDisconnectedEvent callDisconnectedEvent) {
                        Log.i("Spark Call", "Disconnected...");
                    }

                    @Override
                    public void onMediaChanged(MediaChangedEvent mediaChangedEvent) {
                        Log.i("Spark Call", "Media Changed...");
                    }

                    @Override
                    public void onCallMembershipChanged(CallMembershipChangedEvent callMembershipChangedEvent) {
                        Log.i("Spark Call", "Call MemberShip Changed...");
                    }
                };

                WebExTeamsGlobal.call.setObserver(callObserver);
                promise.resolve(true);
            } else {
                Log.e("Spark Phone", "Dialing Failed");
                Log.e("Spark Phone", result.getError().toString());
                promise.reject(new Exception("Dialing Failed " + result.getError().toString()));
            }
        });

    }
```

Any guidance you can provide would be very helpful. Thanks!

**Comment by olivierproffit** [comment]
Ticket answered in 1:1 through our developers' support - https://developer.webex.com/support

**Comment by olivierproffit** [comment]
@mrjaimisra this repo is DEPRECATED, please use https://github.com/webex/webex-android-sdk

**Comment by mrjaimisra** [comment]
@olivierproffit thanks... I guess I submitted on the wrong repo. I have relayed a more complete version of my issue to webex dev support, so I can follow up with them.

**Comment by olivierproffit** [comment]
Followed directly by our dev support
